### ISSUE TITLE
legal/* files

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#11]
check https://github.com/ecommerceberlin/virtual.ecommerceberlin.com/tree/%40dev/pages/legal
 
which should be linked in the footer?

for editing please FORK this project, make changes to your copy and create a PULL REQUEST...then i will incorporate changes

**Comment by az** [comment]
@jprzybylski4 at least let me know which footer links should remain intact :)

**Comment by jprzybylski4** [comment]
Błaszyk is evaluating which ones we should use & rewriting rules for participants.

**Comment by az** [comment]
@jprzybylski4 do we have AT LEAST the list of the documents we will be willing to link to?

**Comment by jprzybylski4** [comment]
We need a similar set to EBE:
imprint - file will be based on imprint.js 
rules for participants - file will be based on visitors.js
rules for sponsors - file will be based on exhibitors.js
cookies - this file needs no changes
personal data processing - file will be based on visitors-data

**Comment by az** [comment]
@jprzybylski4 all files in the repo 

> for editing please FORK this project, make changes to the files in your local repo, push to your github repo and create a PULL REQUEST...then i will incorporate changes
