### ISSUE TITLE
footer - rep people

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#12]
![event opengraph name 2021-03-10 09-26-32](https://user-images.githubusercontent.com/2198/110598988-b5c12e00-8182-11eb-8d34-d9c21df9d981.png)

please confirm who should be displayed in this footer section (fname, lname, position, phone, email address - if differes from already used folks)

**Comment by jprzybylski4** [comment]
confirmed - no difference from EBE - same people, same details
