### ISSUE TITLE
please register already confirmed track sponsors 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#13]
backend is working, some tickets already created

please register sponsors via https://virtadm.ecommerceberlin.com/admin/booking

**if some profile fields are missing please add to them to ALL sponsor-related tickets** via https://virtadm.ecommerceberlin.com/admin/assigninputs

**Comment by az** [comment]
i need cname2, logotype for sure.

**Comment by jprzybylski4** [comment]
done - 3 track sponsors registered
