### ISSUE TITLE
please register SOME already confirmed speakers 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#14]
i need at lease 2, 4 would be optimal

i need full profile data (presenter, cname2, position, logotype, avatar)

ticket is present , please register them via https://virtadm.ecommerceberlin.com/admin/booking

if some profile fields are missing please add them via https://virtadm.ecommerceberlin.com/admin/assigninputs

**Comment by jprzybylski4** [comment]
done - 9 confirmed speakers registered
