### ISSUE TITLE
default opengraph image for SM sharing

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#16]
can be a photo or something intentionally created (photo + text)

**2021 FB prefs re image size are as follows
1200 pixels x 627 pixels**

**Comment by az** [comment]
at the moment it is https://res.cloudinary.com/eventjuicer/image/upload/f_auto/v1615550856/virtualebe_reg.jpg

**Comment by jprzybylski4** [comment]
[opengraph_SM.zip](https://github.com/ecommerceberlin/virtual.ecommerceberlin.com/files/6165428/opengraph_SM.zip)

**Comment by jprzybylski4** [comment]
[opengraph_speaker.zip](https://github.com/ecommerceberlin/virtual.ecommerceberlin.com/files/6165444/opengraph_speaker.zip)

**Comment by jprzybylski4** [comment]
[opengraph_SM.zip](https://github.com/ecommerceberlin/virtual.ecommerceberlin.com/files/6165462/opengraph_SM.zip)
