### ISSUE TITLE
viewer ("visitor") registration confirmation email + sender+ subject

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#17]
need it to configure registration process

please put the content in the comments below

**Comment by jprzybylski4** [comment]
sent from: visitors@ecommerceberlin.com
subject: Registration confirmation for E-commerce Berlin Virtual Edition 2021
body:

Thank you for registering for E-commerce Berlin Virtual Edition, taking place on 26 – 27th May 2021.
We will be in touch with regular updates in the run-up to the show. For more information, including all the conference programmes, please visit our website.
If you have any questions or concerns, just let us know: visitors@ecommerceberlin.com

Danke für die Anmeldung für die E-Commerce Berlin Virtual Edition, die am 26 bis. 27 Mai stattfinden wird.
Wir werden euch kontinuierlich updaten in Bezug auf das Event. Für weitere Informationen besucht unsere Website.
Bei Rückfragen stehen wir euch unter dieser Adresse zur Verfügung: visitors@ecommerceberlin.com

Best,
Lucas Zarna
