### ISSUE TITLE
media, communication partners

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#19]
should there be a 100% clone from EBE, @jprzybylski4 ?

**Comment by jprzybylski4** [comment]
Yes, 100% clone

**Comment by az** [comment]
thx. cloned.
if u need to make some changes @jprzybylski4  please use https://virtadm.ecommerceberlin.com/admin/resources/partners to edit the db of the partners and adapt selected partner-section by editing a widget https://virtadm.ecommerceberlin.com/admin/template accordingly
