### ISSUE TITLE
different video for HERO unit 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#2]
@jprzybylski4 please choose video - give me source video (max resolution)

**Comment by jprzybylski4** [comment]
Based on: https://www.youtube.com/watch?v=l5PUwlIRzRI

1:10-1:14
1:14-1:20
1:39-1:44
1:47-1:52
1:58-2:02
2:05-2:08
1:01-1:06 

Would be perfect if we could use frames without the speaker's details - it won't look good in the background.
If you need a "clean" video without the information bar please let me know. I can have it by tomorrow

**Comment by jprzybylski4** [comment]
Already edited video:
https://drive.google.com/file/d/1oF2cDUein400UtYkTKFzjYNSkFn2-tV4/view?usp=sharing

I guess it just needs to be shortened a bit (25s at the moment)

**Comment by az** [comment]
@jprzybylski4 i have chosen something different -> more "streaming-like experience"=  without auditorium
