### ISSUE TITLE
opengraph image template for speakers profile

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#21]
need sth in the dimensions of https://res.cloudinary.com/eventjuicer/image/upload/c_fit,h_200,q_90,r_max,w_200/g_center,u_ebe5_template_en,x_200,y_0/c_fit,g_center,l_p_120020_logotype,w_300,h_200,x_175,y_0/v1615374091/p_120020_avatar.png

**Comment by az** [comment]
960 × 504 template/background size

**Comment by jprzybylski4** [comment]
[opengraph_speaker.zip](https://github.com/ecommerceberlin/virtual.ecommerceberlin.com/files/6165465/opengraph_speaker.zip)
