### ISSUE TITLE
Change video for HERO unit

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/virtual.ecommerceberlin.com#22]
https://drive.google.com/file/d/133_KKOJcCDO_7bBNcY1slJhUVNM0lpL7/view?usp=sharing

**Comment by az** [comment]
@jprzybylski4 i need universal /cross platform format .... **MP4** (as the source files) MOV is mac/apple proprietary/closed format - useless for web

> MOV is a video format developed by Apple. It is a type of file container that can hold many different video formats and multimedia. ... They are very high quality but have substantial file sizes. MP4 is also a file container, but it is compatible across multiple platforms.

**Comment by jprzybylski4** [comment]
https://drive.google.com/file/d/1PsJQ5dYH3jgurGSixgLXjm1hxGWGF8Qq/view?usp=sharing
