### ISSUE TITLE
/schedule subpage

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#33]
widget order:

**Comment by az** [comment]
@jprzybylski4 please comment :)

**Comment by jprzybylski4** [comment]
The whole layout looks good - it's clear enough for the participants.
Regarding the thematic tracks - we discussed there might be a chance to add the sponsors' logotypes in the legend. Will it be possible?

**Comment by az** [comment]
ok. i assume the answer is "current widgets - schedule+partners are the only widgets that should be displayed here"
