### ISSUE TITLE
configure discord server and chatrooms

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#46]
in return i need (never expiring) invite link to put on the website

**Comment by jprzybylski4** [comment]
https://discord.gg/HDa3RmeZUZ

**Comment by az** [comment]
@jprzybylski4  ![E-commerce Berlin Virtual 2021-05-19 22-28-07](https://user-images.githubusercontent.com/2198/118879864-83098380-b8f1-11eb-9e95-5cfcf9dda563.jpg)

**Comment by jprzybylski4** [comment]
Weird as it has been tested before - the link is tested to never expire and has no limit of uses. 
We've just tested this again, and were able to create new users and join the server.
Could you please double-check it?

**Comment by az** [comment]
i have at least triple checked it :) 
checked again - same story
can you give me an URL to one of the chatrooms? (like https://discord.com/channels/803790453967290418/803790453967290421 )

**Comment by jprzybylski4** [comment]
Could you please check if this one works? 
https://discord.gg/VZW66eUGC9

**Comment by jprzybylski4** [comment]
Just in case - URL to #general channel
https://discord.com/channels/843827859571081256/844226444854558790

**Comment by az** [comment]
@jprzybylski4 this one (https://discord.gg/VZW66eUGC9) works so i will use it on the website
