### ISSUE TITLE
register fake presenters for having EGA ceremony in presentation agenda

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#48]

**Comment by jprzybylski4** [comment]
2 speakers (for stage A&B) registered but they don't show in the agenda. 
Do they need speaker picture to be visible?

**Comment by az** [comment]
![E-commerce Berlin Virtual Edition 2021-05-22 12-44-24](https://user-images.githubusercontent.com/2198/119223801-ac95fb00-bafb-11eb-869d-99c7616f6e41.jpg)

@jprzybylski4 can you please work on it a little? avatar - blank white rectangle.... logotype - must be cropped (removed surrounding white space)

**Comment by az** [comment]
related https://github.com/ecommerceberlin/virtual.ecommerceberlin.com/issues/57

**Comment by jprzybylski4** [comment]
Since I added a white rectangle as the speaker's photo they are also visible on /speakers subpage. 
Can you somehow fix that?
![E-commerce Berlin Virtual Edition 2021-05-22 13-44-06](https://user-images.githubusercontent.com/75311923/119225409-f5ea4880-bb03-11eb-915f-2a93d44dc854.png)

**Comment by az** [comment]
@jprzybylski4 i have not foreseen that ... no chance to filter this out - can you please put the avatar of the host OR  brand signature (aka favicon)?

**Comment by az** [comment]
![E-commerce Berlin Virtual Edition 2021-05-22 13-58-30](https://user-images.githubusercontent.com/2198/119225725-cfc5a800-bb05-11eb-8f0a-084b348cef81.jpg)

can you please add some info? which edition, how many participants, how many categories.... some basic marketing blah blah

**Comment by az** [comment]
@jprzybylski4 perfect!
