### ISSUE TITLE
icons for categories

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#5]
https://material-ui.com/components/material-icons/

**Comment by jprzybylski4** [comment]
- Website Conversion Rate
TrendingUp
- Marketing in E-commerce
ImportantDevices
- New Development in E-commerce
Code
- IT for E-commerce & Cloud
CloudUpload
- Logistics, Delivery, Fulfilment
LocalShipping
- Cross Border Sales / International Growth
Language
- Coronavirus
NewReleases
- Omnichannel Marketplaces
ShoppingBasket
