### ISSUE TITLE
plz replace company logo with transparent version

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#52]
![E-commerce Berlin Virtual Edition 2021-05-20 12-37-43](https://user-images.githubusercontent.com/2198/118964814-38771e00-b968-11eb-802e-a89a410f7128.png)

**Comment by jprzybylski4** [comment]
changed in the admin. Just in case the logotype is available here:
https://res.cloudinary.com/ecommerceberlin/image/upload/v1621510375/criteo_transparent2.png
