### ISSUE TITLE
If possible add Discord link to the registration confirmation email

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/virtual.ecommerceberlin.com#55]
Discord link: https://discord.gg/VZW66eUGC9

**Comment by az** [comment]
https://app.sparkpost.com/templates/edit/virtual-viewer-registration/published/content

**Comment by az** [comment]
@jprzybylski4 added. send me updated (bilingual) full copy if you want it changed (current version below)

> 
> Hello !
> 
> Thank you for registering for E-commerce Berlin Virtual Edition, taking place on 26 – 27th May 2021.
> 
> Join our discord server https://discord.gg/VZW66eUGC9 to interact with the speakers and other participants!
> 
> If you have any questions or concerns, just let us know: visitors@ecommerceberlin.com
> 
> Danke für die Anmeldung für die E-Commerce Berlin Virtual Edition, die am 26 bis. 27 Mai stattfinden wird.
> 
> Wir werden euch kontinuierlich updaten in Bezug auf das Event. Für weitere Informationen besucht unsere Website.
> 
> Bei Rückfragen stehen wir euch unter dieser Adresse zur Verfügung: visitors@ecommerceberlin.com
> 
> Best,
> 
> Lucas Zarna
