### ISSUE TITLE
translations needed for additional profile fields

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#56]
![26-27 May, two days full of knowledge  Join now for free! 2021-05-21 12-35-20](https://user-images.githubusercontent.com/2198/119124526-0d0c3600-ba31-11eb-84a9-8b1ef56350ec.jpg)

**Comment by EragonRD** [comment]
Hi , i'm free to  help you. Can you send me the document to translate at my email ? 

debbah.rabah.amir@gmail.com

**Comment by jprzybylski4** [comment]
done

**Comment by EragonRD** [comment]
Can you send to me the word document , i mean what you want to translate
and the language .

Le ven. 21 mai 2021 à 17:52, jprzybylski4 ***@***.***> a
écrit :

**Comment by az** [comment]
@EragonRD thx - we have sorted it out internally :)
