### ISSUE TITLE
Change confirmation email 

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/virtual.ecommerceberlin.com#61]
Full copy:

Hello !

Thank you for registering for the E-commerce Berlin Virtual Edition, taking place on 26 – 27th May 2021.

Join our discord server https://discord.gg/VZW66eUGC9 to interact with the speakers and other participants!

If you have any questions or concerns, just let us know: visitors@ecommerceberlin.com

Danke für die Anmeldung für die E-Commerce Berlin Virtual Edition, die am 26 bis. 27 Mai stattfinden wird.

Trete unserem Discord-Server https://discord.gg/VZW66eUGC9 bei, um mit den Speakers und anderen Teilnehmern zu interagieren!

Bei Rückfragen stehen wir euch unter dieser Adresse zur Verfügung: visitors@ecommerceberlin.com

Best,

Lucas Zarna

**Comment by az** [comment]
updated
