### ISSUE TITLE
25/06 1pm - change email registration template - add stream access link 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#64]
@jprzybylski4 can you provide german copy?

**Comment by jprzybylski4** [comment]
FULL COPY:

Hello !

Thank you for registering for the E-commerce Berlin Virtual Edition, taking place on 26 – 27th May 2021.

You can access the streaming using this link: https://virtual.ecommerceberlin.com/recall/[[token]]

Join our discord server https://discord.gg/VZW66eUGC9 to interact with the speakers and other participants!

Danke für die Anmeldung für die E-Commerce Berlin Virtual Edition, die am 26 bis. 27 Mai stattfinden wird.

Über diesen Link kann man auf das Streaming zugreifen: https://virtual.ecommerceberlin.com/recall/[[token]]

Trete unserem Discord-Server https://discord.gg/VZW66eUGC9 bei, um mit den Speakers und anderen Teilnehmern zu interagieren!

Best,

Lucas Zarna

**Comment by az** [comment]
https://app.sparkpost.com/templates/edit/virtual-viewer-registration/published/content
