### ISSUE TITLE
video_length_minutes

### ISSUE THREAD

**Issue by az** [ecommerceberlin/virtual.ecommerceberlin.com#65]
triple check it please and i would also count in the Q&A session (otherwise it might be badly percepted by speakers)

**Comment by jprzybylski4** [comment]
Day 1 checked & adjusted.
Day 2 will be done tomorrow once I have all the final files.

**Comment by az** [comment]
@jprzybylski4 nice!

**Comment by az** [comment]
@jprzybylski4 zakładam, że masz to na uwadzę i pójdzie dzisiaj jeszcze ew. update, right?

**Comment by jprzybylski4** [comment]
Day2 done
